# Generated by Django 3.0.5 on 2020-05-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmyteacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='school_id',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='supply_cost',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(default='2', max_length=64),
            preserve_default=False,
        ),
    ]
