# Generated by Django 3.0.5 on 2020-05-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmyteacher', '0002_auto_20200503_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='school_id',
            field=models.IntegerField(default=1),
        ),
    ]
