# Generated by Django 3.0.5 on 2020-06-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('supply_list', models.CharField(max_length=256)),
                ('supply_cost', models.FloatField()),
                ('school_id', models.IntegerField(default=1)),
            ],
        ),
    ]
