# Generated by Django 3.0.5 on 2020-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmyclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='school_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='supply_cost',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
