# Generated by Django 3.0.5 on 2020-06-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundmyclass', '0003_auto_20200609_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='supply_cost',
            field=models.FloatField(),
        ),
    ]
